version: "3.8"

volumes:
  todo-nest-db-volume:

services:
  todo-nest-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - todo-nest-db-volume:/var/lib/postgresql/data
    ports: 
      - ${POSTGRES_PORT:-5435}:5432
  